### ISSUE TITLE
Add prompt modal

### ISSUE THREAD

**Issue by jannydiamond** [on3iro/radlands-digital#137]
We need a prompt modal for the following cases:

* [ ] Waiting for opponent to resolve... could be one
* [ ] Vangard > Opponent should do damage back
* [ ] Famine > Choose card to keep

**Comment by on3iro** [comment]
@jannydiamond waiting for isn't one I think, because it is not a prompt... at least not, yet... we could make it one, so that you could dismiss the message... but do we actually want this? usually not, I think...I would postpone changing that one  for now.
